### PR TITLE
Add a new function "string_set_char_at"

### PR DESCRIPTION
**Pull request by ahueck**
Add a function "string_set_char_at" (and unit tests) which corresponds to "string_char_at" in order to be able to set an abritary char in a string.
Indexing is identical to "string_char_at".
Example call:  string_set_char_at(1 "hello" a) -> returns "hallo"

### CODE REVIEW

**Comment by toeb** [comment]
Hi, 

thanks again!  I have a problem with the string functions - they are not consistent currently and especially `string_char_at`'s signature is no good.  I currently do not have the time but I want to change all string functions to adhere to the following interface `<function name>(<subject:<string>> <other parameter>...)-><result:<any>>` .   Would you mind to change the interface of `string_char_at` and string_set_char_at`  to move the index away from first position? 

Also:  Please rename your function to `string_char_at_set`  I know it does not seem as intuitive as `string_set_char_at` but it is more consistent   `<subject>_<command>_<subcommand>`.  The Idea behind that is that to have normalized names because of missing namespaces in the cmake language (which would otherwise create problems when dealing with many functions as `cmakepp` does)

**Comment by ahueck** [comment]
I have tried to update both functions according to your suggestions. Additionally, I updated the unit tests for the existing "string_char_at" function. It consists of similar tests as the new one now.
I propose to update the documentation of both in a different change set, to keep everything as consistent as possible.

**Comment by toeb** [comment]
well something went wrong. A lot of my string handling functions do not work any more.

**Comment by toeb** [comment]
alright!  thanks its merged :D

**Pull request merged**
